name: Lint

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno check
        run: |
          deno check src/main.ts
      - name: Deno lint
        run: |
          deno lint
